import { db } from '@appdeploy/sdk';
import { decisionMesh } from './decision-mesh';
export async function adaptiveWorkspace(profile:any){
  const mesh=await decisionMesh(profile);
  const [demands,quotes,trades]=await Promise.all([db.list<any>('demands',{limit:80}),db.list<any>('quotes',{limit:80}),db.list<any>('trades',{limit:80})]);
  const ownDemands=demands.items.filter((x:any)=>profile.role==='operator'||x.ownerUserId===profile.userId);
  const ownQuotes=quotes.items.filter((x:any)=>profile.role==='operator'||x.ownerUserId===profile.userId);
  const ownTrades=trades.items.filter((x:any)=>profile.role==='operator'||x.ownerUserId===profile.userId);
  const verified=profile.role==='operator'||profile.verificationStatus==='verified';
  const activeTrades=ownTrades.filter((x:any)=>x.status!=='Settled');
  const pendingReviews=(mesh.cards||[]).filter((x:any)=>x.decision==='REVIEW'||x.priority==='critical');
  const primary=profile.role==='buyer'?(verified?{title:'Your next sourcing move',subtitle:ownDemands.length?'Review your highest-priority demand and qualified supply.':'Start with one requirement and let Tradevance structure the sourcing path.',action:'Buyer Workspace',label:'Open sourcing'}:{title:'Your workspace is waiting for verification',subtitle:'Complete organization verification before RFQs, introductions and other transactional actions can be enabled.',action:'Profile & Verification',label:'Complete verification'}):profile.role==='seller'?(verified?{title:'Your next commercial move',subtitle:'Keep capability current and focus on the buyer demand with the strongest fit and evidence.',action:'Buyer Network',label:'View buyer demand'}:{title:'Build trust before chasing demand',subtitle:'Complete organization verification so Tradevance can qualify your supply and unlock transactional actions.',action:'Profile & Verification',label:'Complete verification'}):{title:pendingReviews.length?`You have ${pendingReviews.length} decisions to review`:'Operations are clear',subtitle:pendingReviews.length?'Start with the highest-impact risk or opportunity and open the governed workspace.':'Monitor risk, opportunity, execution and data quality from one view.',action:'Decision Mesh',label:'Open Decision Mesh'};
  const contextCards=(mesh.cards||[]).slice(0,4).map((x:any)=>({id:x.id,title:x.title,subtitle:x.subtitle||x.detail||'Tradevance signal',decision:x.decision||'RECOMMEND',priority:x.priority||'medium',score:Number(x.score||x.confidence||0),reason:x.why||x.reason||'Observed from current Tradevance intelligence.',destination:x.destination||'Decision Mesh',dataQuality:x.dataQuality||'Observed'}));
  return {role:profile.role,verified,greeting:profile.role==='buyer'?'Welcome back, Buyer':profile.role==='seller'?'Welcome back, Seller':'Operator overview',company:profile.company||profile.name||'Your organization',primary,stats:{activeTrades:activeTrades.length,demands:ownDemands.length,quotes:ownQuotes.length,signals:(mesh.cards||[]).length,learningSamples:Number(mesh.memory?.learningSamples||0)},contextCards,privacy:'Role-scoped workspace. Private contacts and hidden counterparty information are never returned.',policy:'Adaptive guidance only. No contract, payment, quote, approval, or trade execution is performed by this endpoint.'};
}