import { db } from '@appdeploy/sdk';
import { evaluateCounterpartyRisk } from './risk';
function num(v:any){const n=Number(v);return Number.isFinite(n)?n:0;}
function norm(v:any){return String(v||'').toLowerCase().normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').replace(/\s+/g,' ').trim();}
function productFlag(product:string){const p=norm(product);if(!p)return{penalty:8,flag:'Product is unspecified.'};if(['diesel','jet fuel','caustic soda','sulphur','ammonia','chlorine'].some(x=>p.includes(x)))return{penalty:4,flag:'Special-handling commodity policy flag; verify product, quality and regulatory documents.'};return{penalty:0,flag:''};}
function evaluateDeal(cp:any,deal:any,portfolioValue:number){const reasons=[...cp.reasons];let score=cp.riskScore;const product=productFlag(deal.product);score-=product.penalty;const flags:string[]=[];if(product.flag)flags.push(product.flag);if(!deal.product)reasons.push('Product specification is incomplete.');if(!deal.destination){score-=6;reasons.push('Destination is missing or unconfirmed.');}if(!deal.incoterm){score-=6;reasons.push('Incoterm is missing or unconfirmed.');}const payment=norm(deal.payment);if(!payment){score-=8;reasons.push('Payment terms are not stated.');}else if(payment.includes('to be negotiated')||payment.includes('open account')){score-=5;reasons.push('Payment terms require additional counterparty/finance review.');}const value=num(deal.transactionValue||deal.value||0);if(value>5000000){score-=5;reasons.push('Material transaction value requires enhanced review.');}if(value>20000000){score-=6;reasons.push('High transaction value requires stronger evidence and approval.');}if(portfolioValue>0&&value/portfolioValue>=0.25){score-=8;reasons.push('Deal is concentrated relative to current active trade value.');}const docs=Array.isArray(deal.documents)?deal.documents.length:0;if(['quote','trade'].includes(String(deal.dealType))&&docs===0){score-=5;reasons.push('No transaction-document evidence is attached yet.');}score=Math.max(0,Math.min(100,Math.round(score)));let decision=cp.decision;if(decision==='ALLOW'){if(score<60)decision='BLOCK';else if(score<80||product.penalty>0||value>5000000||docs===0&&deal.dealType!=='rfq')decision='REVIEW';}if(!reasons.length)reasons.push('Counterparty cleared and deal completeness/risk signals are within policy thresholds.');return{decision,riskScore:score,riskBand:score>=85?'Low':score>=70?'Medium':score>=55?'High':'Critical',reasons,flags,counterparty:cp,deal:{dealType:deal.dealType||'unknown',product:deal.product||'',destination:deal.destination||'',incoterm:deal.incoterm||'',payment:deal.payment||'',transactionValue:value,documents:docs},policy:'Decision support only. Not credit underwriting, legal clearance, sanctions legal advice or guaranteed deal profitability.'};}
export async function evaluateDealRisk(p:any,deal:any={}){const trades=await db.list<any>('trades',{limit:200});const portfolioValue=trades.items.filter((x:any)=>x.status!=='Settled').reduce((a:number,x:any)=>a+num(x.value),0);const cp=await evaluateCounterpartyRisk(p,{transactionValue:num(deal.transactionValue||deal.value||0),product:deal.product||'',destination:deal.destination||''});return evaluateDeal(cp,deal,portfolioValue);}
export async function dealRiskSnapshot(){const [profiles,demands,quotes,trades]=await Promise.all([db.list<any>('profiles',{limit:300}),db.list<any>('demands',{limit:100}),db.list<any>('quotes',{limit:100}),db.list<any>('trades',{limit:100})]);const active=trades.items.filter((x:any)=>x.status!=='Settled');const portfolioValue=active.reduce((a:number,x:any)=>a+num(x.value),0);const rows:any[]=[];for(const q of quotes.items.slice(-30).reverse()){const p=profiles.items.find((x:any)=>x.userId===q.ownerUserId);if(p){const value=num(q.quantity)*num(q.price);const cp=await evaluateCounterpartyRisk(p,{transactionValue:value,product:q.product});const r=evaluateDeal(cp,{dealType:'quote',product:q.product,payment:q.payment,incoterm:q.incoterm,destination:q.destination,transactionValue:value,documents:q.documents||[]},portfolioValue);rows.push({id:q.id,type:'Quote',company:p.company||p.name||'—',product:q.product,value,...r});}}
for(const d of demands.items.slice(-20).reverse()){const p=profiles.items.find((x:any)=>x.userId===d.ownerUserId);if(p){const r=await evaluateDealRisk(p,{dealType:'rfq',product:d.product,payment:d.payment,incoterm:d.incoterm,destination:d.destination,transactionValue:num(d.price)*num(d.quantity)});rows.push({id:d.id,type:'RFQ',company:p.company||p.name||'—',product:d.product,value:num(d.price)*num(d.quantity),...r});}}
for(const t of trades.items.filter((x:any)=>x.status!=='Settled').slice(-20).reverse()){const p=profiles.items.find((x:any)=>x.userId===t.ownerUserId);if(p){const r=await evaluateDealRisk(p,{dealType:'trade',product:t.product,payment:t.payment,incoterm:t.incoterm,destination:t.destination,transactionValue:num(t.value),documents:t.documents||[]});rows.push({id:t.id,type:'Trade',company:p.company||p.name||'—',product:t.product,value:num(t.value),...r});}}
return{total:rows.length,allow:rows.filter(x=>x.decision==='ALLOW').length,review:rows.filter(x=>x.decision==='REVIEW').length,block:rows.filter(x=>x.decision==='BLOCK').length,portfolioValue,rows:rows.slice(0,50),policy:'Deal Guardian is decision support. REVIEW and BLOCK are held by the transactional gate; AI cannot override them.'};}