import { db } from '@appdeploy/sdk';
import { evaluateDealRisk } from './deal-risk';
function num(v:any){const n=Number(v);return Number.isFinite(n)?n:0;}
const PLAN_VALUE:Record<string,number>={seller_verified:99,seller_pro:299,buyer_pro:79};
const FREE_PLANS=new Set(['seller_free','buyer_free','operator']);
const TX_FEE_RATE=0.005;
function actionFor(row:any){if(row.decision==='BLOCK')return{action:'Resolve compliance/risk blockers before any commercial progression.',approval:'Compliance + Risk Review'};if(row.decision==='REVIEW')return{action:'Complete manual risk review and required evidence before approval.',approval:'Trade Risk Approval'};if(row.marginReadiness!=='READY')return{action:'Capture acquisition cost / cost basis before treating margin as decision-ready.',approval:'Commercial Review'};if(row.documents===0&&row.type!=='RFQ')return{action:'Attach transaction evidence/documents before execution.',approval:'Document Review'};return{action:'Proceed to next approved commercial step.',approval:'Standard Human Approval'};}
export async function executionIntelligence(){const [profiles,demands,quotes,trades]=await Promise.all([db.list<any>('profiles',{limit:300}),db.list<any>('demands',{limit:150}),db.list<any>('quotes',{limit:150}),db.list<any>('trades',{limit:150})]);const activeTrades=trades.items.filter((x:any)=>x.status!=='Settled');const portfolioValue=activeTrades.reduce((a:number,x:any)=>a+num(x.value),0);const rows:any[]=[];for(const q of quotes.items.slice(-40).reverse()){const p=profiles.items.find((x:any)=>x.userId===q.ownerUserId);if(!p)continue;const value=num(q.quantity)*num(q.price);const r=await evaluateDealRisk(p,{dealType:'quote',product:q.product,payment:q.payment,incoterm:q.incoterm,destination:q.destination,transactionValue:value,documents:q.documents||[]});const costBasis=num(q.acquisitionCost||q.supplierCost||q.costBasis);const margin=costBasis>0?value-costBasis:null;const marginPct=costBasis>0?((value-costBasis)/value)*100:null;const riskAdjustedValue=value*(r.riskScore/100);const docs=Array.isArray(q.documents)?q.documents.length:0;const row={id:q.id,type:'Quote',company:p.company||p.name||'—',role:p.role,product:q.product||'—',value,riskAdjustedValue,riskScore:r.riskScore,decision:r.decision,documents:docs,margin,marginPct:marginPct===null?null:Math.round(marginPct*10)/10,marginReadiness:costBasis>0?'READY':'INSUFFICIENT_COST_DATA',plan:p.plan||'—'};Object.assign(row,actionFor(row));rows.push(row);}
for(const t of activeTrades.slice(-30).reverse()){const p=profiles.items.find((x:any)=>x.userId===t.ownerUserId);if(!p)continue;const value=num(t.value);const r=await evaluateDealRisk(p,{dealType:'trade',product:t.product,payment:t.payment,incoterm:t.incoterm,destination:t.destination,transactionValue:value,documents:t.documents||[]});const costBasis=num(t.acquisitionCost||t.supplierCost||t.costBasis);const margin=costBasis>0?value-costBasis:null;const marginPct=costBasis>0?((value-costBasis)/value)*100:null;const row={id:t.id,type:'Trade',company:p.company||p.name||'—',role:p.role,product:t.product||'—',value,riskAdjustedValue:value*(r.riskScore/100),riskScore:r.riskScore,decision:r.decision,documents:Array.isArray(t.documents)?t.documents.length:0,margin,marginPct:marginPct===null?null:Math.round(marginPct*10)/10,marginReadiness:costBasis>0?'READY':'INSUFFICIENT_COST_DATA',plan:p.plan||'—'};Object.assign(row,actionFor(row));rows.push(row);}
const activeRows=rows.filter(x=>x.value>0);const riskAdjustedPortfolio=activeRows.reduce((a:number,x:any)=>a+x.riskAdjustedValue,0);const illustrativeFeeOpportunity=Math.round(riskAdjustedPortfolio*TX_FEE_RATE*100)/100;const actualPlanSignals=profiles.items.filter((p:any)=>!FREE_PLANS.has(p.plan||'')).length;const upgradeRows=profiles.items.filter((p:any)=>FREE_PLANS.has(p.plan||'')&&p.role!=='operator').map((p:any)=>{const target=p.role==='seller'?'seller_pro':'buyer_pro';return{userId:p.userId,company:p.company||p.name||'—',role:p.role,currentPlan:p.plan||'—',recommendedPlan:target,monthlyUpside:PLAN_VALUE[target]||0,action:'Position premium plan after verification and first qualified commercial workflow.'};}).filter((x:any)=>x.monthlyUpside>0).slice(0,30);
const actualTradeValue=trades.items.reduce((a:number,t:any)=>a+num(t.value),0);const actualRevenueSignalCount=actualPlanSignals;return{generatedAt:new Date().toISOString(),actual:{tradeValue:actualTradeValue,paidPlanSignals:actualRevenueSignalCount,note:'Actual revenue is not asserted without a connected payment processor and settled billing records.'},dealEconomics:{deals:activeRows.length,activeValue:activeRows.reduce((a:number,x:any)=>a+x.value,0),riskAdjustedValue:Math.round(riskAdjustedPortfolio*100)/100,avgRiskScore:activeRows.length?Math.round(activeRows.reduce((a:number,x:any)=>a+x.riskScore,0)/activeRows.length):0,marginReady:activeRows.filter(x=>x.marginReadiness==='READY').length,marginMissingCostBasis:activeRows.filter(x=>x.marginReadiness!=='READY').length},revenueOpportunity:{illustrativeTransactionFeeRate:TX_FEE_RATE,illustrativeTransactionFeeOpportunity,note:'Illustrative planning assumption only; not actual revenue, invoice, or contracted fee.',subscriptionUpgradeOpportunity:upgradeRows.reduce((a:number,x:any)=>a+x.monthlyUpside,0),subscriptionUpgradeMonthly:upgradeRows.reduce((a:number,x:any)=>a+x.monthlyUpside,0),subscriptionUpgradeRows:upgradeRows},approval:{allow:activeRows.filter(x=>x.decision==='ALLOW').length,review:activeRows.filter(x=>x.decision==='REVIEW').length,block:activeRows.filter(x=>x.decision==='BLOCK').length},rows:activeRows.slice(0,50),portfolioValue,policy:'Execution Intelligence is decision support. No payment, contract, billing record, or revenue recognition is created by this endpoint.'};}
