import { db, ai } from '@appdeploy/sdk';

export const ingestionSources=[
{id:'comtrade',name:'UN Comtrade',category:'Official trade statistics',purpose:'Country-by-product trade flows and HS-level import/export context.',access:'API / programmatic integration',status:'INTEGRATION',url:'https://comtradeplus.un.org/',next:'Configure authenticated ingestion and scheduled delta sync.'},
{id:'itc-trade-map',name:'ITC Trade Map',category:'Trade intelligence',purpose:'Trade flows, market-share and product-country analysis.',access:'Licensed workspace / API boundary',status:'INTEGRATION',url:'https://www.trademap.org/',next:'Confirm commercial access and connector credentials.'},
{id:'opensanctions',name:'OpenSanctions',category:'Sanctions / PEP screening',purpose:'Entity matching and sanctions/PEP risk screening.',access:'API key required',status:'AUTH_REQUIRED',url:'https://www.opensanctions.org/docs/api/',next:'Provision OPENSANCTIONS_API_KEY and enable entity /match screening.'},
{id:'registries',name:'National company registries',category:'KYB / legal identity',purpose:'Legal existence, registration identifiers and jurisdiction evidence.',access:'Country-specific APIs / paid access',status:'INTEGRATION',url:'https://www.gov.uk/get-information-about-a-company',next:'Build jurisdiction-specific registry adapters.'},
{id:'shipment',name:'Licensed shipment intelligence',category:'Shipment / logistics',purpose:'Shipment history, lanes, exporter/importer evidence and recency.',access:'Licensed provider',status:'LICENSE_REQUIRED',url:'https://www.volza.com/',next:'Select provider and map shipment entities into the Trust Graph.'},
{id:'fx',name:'FX / payment infrastructure',category:'Commercial execution',purpose:'FX rates, payment status and settlement signals.',access:'Payment / FX provider',status:'INTEGRATION',url:'https://www.ecb.europa.eu/stats/policy_and_exchange_rates/euro_reference_exchange_rates/html/index.en.html',next:'Choose a production FX/payment provider and implement signed callbacks.'}
];

const normalize=(v:string)=>String(v||'').toLowerCase().replace(/&/g,'and').replace(/[^a-z0-9]+/g,' ').trim().replace(/\s+/g,' ');
const domain=(url:string)=>{try{return new URL(url).hostname.replace(/^www\./,'').toLowerCase()}catch{return ''}};
const tokenSet=(v:string)=>new Set(normalize(v).split(' ').filter(x=>x.length>2));
function overlap(a:string,b:string){const A=tokenSet(a),B=tokenSet(b);if(!A.size||!B.size)return 0;let n=0;for(const x of A)if(B.has(x))n++;return n/Math.max(A.size,B.size);}
function resolutionScore(a:any,b:any){const name=overlap(a.name,b.name);const country=normalize(a.country)===normalize(b.country)?1:0;const da=domain(a.officialUrl),dbb=domain(b.officialUrl);const web=da&&dbb&&da===dbb?1:0;const prod=overlap((a.products||[]).join(' '),(b.products||[]).join(' '));const reg=a.registrationNumber&&b.registrationNumber&&normalize(a.registrationNumber)===normalize(b.registrationNumber)?1:0;return Math.round(Math.min(100,(name*55)+(country*15)+(web*20)+(prod*10)+(reg*40)));}
async function tableCount(table:string){const r=await db.list<any>(table,{limit:200});return r.items.length;}
export async function entityResolutionSnapshot(){const rows=(await db.list<any>('entities',{limit:200})).items;const seen=new Map<string,any[]>();for(const e of rows){const key=normalize((e.legalName||e.name||'')+'|'+(e.country||''));if(!key.replace('|',''))continue;const arr=seen.get(key)||[];arr.push(e);seen.set(key,arr);}const duplicateGroups=[...seen.entries()].filter(([,v])=>v.length>1).map(([key,v])=>({key,entityIds:v.map(x=>x.id),names:v.map(x=>x.name),reason:'Exact normalized name + country collision',confidence:96}));const candidates:any[]=[];for(let i=0;i<rows.length;i++){for(let j=i+1;j<rows.length;j++){const a=rows[i],b=rows[j];if(normalize(a.name)===normalize(b.name)&&normalize(a.country)!==normalize(b.country))continue;const score=resolutionScore(a,b);if(score>=72&&score<96)candidates.push({leftId:a.id,rightId:b.id,left:a.name,right:b.name,score,reason:score>=88?'Strong name/evidence similarity':'Potential duplicate; manual review required'});}}
return{canonicalEntities:rows.length,duplicateGroups:duplicateGroups.length,duplicateRecords:duplicateGroups.reduce((n,g)=>n+g.entityIds.length-1,0),candidatePairs:candidates.sort((a,b)=>b.score-a.score).slice(0,30),unresolvedConflicts:candidates.filter(x=>x.score<88).length,policy:'Conservative merge policy: exact high-confidence identity collisions can be grouped; ambiguous matches require operator review and never auto-merge.'};}
export async function ingestionSnapshot(){const [raw,evidence,entities,demands,opportunities,runs,resolution]=await Promise.all([tableCount('raw_evidence'),tableCount('normalized_evidence'),tableCount('entities'),tableCount('demands'),tableCount('opportunities'),tableCount('ingestion_runs'),entityResolutionSnapshot()]);const last=(await db.list<any>('ingestion_runs',{limit:50})).items.sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt))).slice(0,20);return{pipeline:{rawEvidence:raw,normalizedEvidence:evidence,resolvedEntities:entities,operationalDemands:demands,opportunities,ingestionRuns:runs},resolution,sources:ingestionSources,lastRuns:last};}
export async function runSourceHealth(sourceId:string,actorId:string){const source=ingestionSources.find(x=>x.id===sourceId);if(!source)throw new Error('Unknown ingestion source');const createdAt=new Date().toISOString();if(source.status==='AUTH_REQUIRED'||source.status==='LICENSE_REQUIRED'){const [id]=await db.add('ingestion_runs',[{sourceId,sourceName:source.name,checkType:'gate',status:'BLOCKED',syncStatus:'NOT_CONNECTED',createdAt,actorId,note:'Provider credential or commercial license is required before live ingestion.'}]);return{id,status:'BLOCKED',syncStatus:'NOT_CONNECTED',note:'Provider credential or commercial license is required before live ingestion.'};}try{const scraped=await ai.scrape({url:source.url});const healthy=scraped.status>=200&&scraped.status<400&&Boolean(scraped.text);const [id]=await db.add('ingestion_runs',[{sourceId,sourceName:source.name,checkType:'source_health',status:healthy?'HEALTHY':'UNHEALTHY',syncStatus:'NOT_CONNECTED',httpStatus:scraped.status,title:scraped.title||'',contentLength:scraped.text?.length||0,createdAt,actorId,note:healthy?'Public source documentation reachable; data connector is not yet authenticated/ingesting.':'Source returned an unusable response; no data was written.'}]);return{id,status:healthy?'HEALTHY':'UNHEALTHY',syncStatus:'NOT_CONNECTED',httpStatus:scraped.status,title:scraped.title||'',note:healthy?'Public source documentation reachable; data connector is not yet authenticated/ingesting.':'Source returned an unusable response; no data was written.'};}catch{const [id]=await db.add('ingestion_runs',[{sourceId,sourceName:source.name,checkType:'source_health',status:'ERROR',syncStatus:'NOT_CONNECTED',createdAt,actorId,note:'Health check failed safely; no source data was written.'}]);return{id,status:'ERROR',syncStatus:'NOT_CONNECTED',note:'Health check failed safely; no source data was written.'};}}
