import { db, ai } from '@appdeploy/sdk';

export const officialSources=[
{id:'ofac',name:'OFAC Sanctions List Service',jurisdiction:'US',url:'https://ofac.treasury.gov/sanctions-list-service',structuredUrl:'https://ofac.treasury.gov/sanctions-list-service'},
{id:'unsc',name:'UN Security Council Consolidated List',jurisdiction:'UN',url:'https://main.un.org/securitycouncil/en/content/un-sc-consolidated-list',structuredUrl:'https://main.un.org/securitycouncil/en/content/un-sc-consolidated-list'},
{id:'uk',name:'UK Sanctions List',jurisdiction:'UK',url:'https://www.gov.uk/government/publications/the-uk-sanctions-list',structuredUrl:'https://sanctionslist.fcdo.gov.uk/docs/UK-Sanctions-List.xml'}
];
function norm(v:string){return String(v||'').toLowerCase().normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/&/g,' and ').replace(/[^a-z0-9]+/g,' ').replace(/\s+/g,' ').trim();}
function tokens(v:string){return new Set(norm(v).split(' ').filter(x=>x.length>=3));}
function overlap(a:string,b:string){const aa=tokens(a),bb=tokens(b);if(!aa.size||!bb.size)return 0;let hit=0;aa.forEach(x=>{if(bb.has(x))hit++});return hit/Math.max(aa.size,bb.size);}
function fingerprint(p:any){return norm((p.legalName||p.company||p.name||'')+'|'+(p.country||''));}
async function fetchOfficial(source:any){const r=await ai.scrape({url:source.url});if(r.status>=400||!r.text)return{sourceId:source.id,source:source.name,status:'UNAVAILABLE',text:'',httpStatus:r.status,title:r.title||''};return{sourceId:source.id,source:source.name,status:'HEALTHY',text:r.text.slice(0,900000),httpStatus:r.status,title:r.title||''};}
async function fetchStructured(source:any){const r=await ai.scrape({url:source.structuredUrl});if(r.status>=400||!r.text)return{sourceId:source.id,source:source.name,status:'UNAVAILABLE',text:'',httpStatus:r.status,title:r.title||''};return{sourceId:source.id,source:source.name,status:'HEALTHY',text:r.text.slice(0,900000),httpStatus:r.status,title:r.title||''};}
function findCandidate(name:string,text:string){const n=norm(name);if(!n)return{score:0,kind:'none',snippet:''};const idx=text.toLowerCase().indexOf(n);if(idx>=0)return{score:100,kind:'exact',snippet:text.slice(Math.max(0,idx-220),idx+Math.min(520,n.length+260))};const compact=text.split(/[\n\r|<>]+/).map(x=>x.trim()).filter(Boolean);let best={score:0,kind:'none',snippet:''};for(const line of compact){const s=overlap(name,line);if(s>best.score)best={score:s*100,kind:s>=0.8?'strong':'weak',snippet:line.slice(0,700)};}return best;}
export async function syncOfficialSources(actorId:string){const results=[];for(const source of officialSources){const fetched=await fetchOfficial(source);const createdAt=new Date().toISOString();const snapshot={sourceId:source.id,sourceName:source.name,jurisdiction:source.jurisdiction,status:fetched.status,fetchedAt:createdAt,httpStatus:fetched.httpStatus,title:fetched.title,content:fetched.text,contentLength:fetched.text.length,sourceUrl:source.url,syncUrl:source.structuredUrl,versionFingerprint:norm(fetched.text.slice(0,25000)),actorId};const [id]=await db.add('official_sanctions_snapshots',[snapshot]);results.push({id,sourceId:source.id,source:source.name,status:fetched.status,fetchedAt:createdAt,httpStatus:fetched.httpStatus,contentLength:fetched.text.length});}await db.add('audit',[{userId:actorId,action:'official_sanctions_sync',sources:results.map(x=>x.sourceId),createdAt:new Date().toISOString()}]);return results;}
export async function officialSnapshotStatus(){const rows=(await db.list<any>('official_sanctions_snapshots',{limit:50})).items;return officialSources.map(s=>{const latest=rows.filter(x=>x.sourceId===s.id).sort((a,b)=>String(b.fetchedAt).localeCompare(String(a.fetchedAt)))[0];return{id:s.id,name:s.name,status:latest?.status||'NOT_SYNCED',fetchedAt:latest?.fetchedAt||null,httpStatus:latest?.httpStatus||null,contentLength:Number(latest?.contentLength||0),sourceUrl:s.url};});}
async function latestText(sourceId:string){const rows=(await db.list<any>('official_sanctions_snapshots',{limit:50})).items.filter(x=>x.sourceId===sourceId&&x.status==='HEALTHY').sort((a,b)=>String(b.fetchedAt).localeCompare(String(a.fetchedAt)));const latest=rows[0];if(!latest)return null;const age=Date.now()-Date.parse(latest.fetchedAt||'');if(!Number.isFinite(age)||age>72*60*60*1000)return null;return latest;}
export async function officialScreen(p:any){const name=String(p.legalName||p.company||p.name||'').trim();const country=String(p.country||'').trim();if(!name)return{status:'SCREENING_UNAVAILABLE',reason:'Legal/company name is missing.',sources:[]};const fp=fingerprint(p);const cache=(await db.list<any>('compliance_screenings',{limit:100})).items.find((x:any)=>x.fingerprint===fp&&Date.now()-Date.parse(x.createdAt||'')<86400000);if(cache)return cache.result;const fetched=await Promise.all(officialSources.map(async s=>{const latest=await latestText(s.id);return latest?{sourceId:s.id,source:s.name,status:'HEALTHY',text:latest.content,httpStatus:latest.httpStatus,fetchedAt:latest.fetchedAt}:{sourceId:s.id,source:s.name,status:'UNAVAILABLE',text:'',httpStatus:0};}));const unavailable=fetched.filter(x=>x.status!=='HEALTHY');if(unavailable.length===officialSources.length)return{status:'SCREENING_UNAVAILABLE',reason:'All official source snapshots are unavailable or stale.',fingerprint:fp,sources:fetched.map(x=>({id:x.sourceId,name:x.source,status:x.status,httpStatus:x.httpStatus}))};const matches=fetched.filter(x=>x.status==='HEALTHY').map(x=>{const c=findCandidate(name,x.text);return{sourceId:x.sourceId,source:x.source,score:Math.round(c.score),kind:c.kind,snippet:c.snippet};}).filter(x=>x.score>=72).sort((a,b)=>b.score-a.score);const exact=matches.some(x=>x.score>=100);const strong=matches.some(x=>x.score>=88);const result={status:exact?'MATCH_BLOCKED':strong?'POTENTIAL_MATCH_REVIEW':matches.length?'POTENTIAL_MATCH_REVIEW':unavailable.length?'SCREENING_UNAVAILABLE':'PRE_SCREEN_CLEAR',reason:exact?'Exact name occurrence found in an official sanctions source.':strong?'Strong name similarity requires manual review.':matches.length?'Potential name similarity requires manual review.':unavailable.length?'One or more official source snapshots are unavailable; no clearance asserted.':'No potential name match found in the checked official source snapshots.',fingerprint:fp,subject:{name,country},sources:fetched.map(x=>({id:x.sourceId,name:x.source,status:x.status,httpStatus:x.httpStatus,fetchedAt:x.fetchedAt||null})),matches,checkedAt:new Date().toISOString(),scope:'Company/entity pre-screen only; not legal clearance, UBO/KYB, PEP, adverse-media, or jurisdiction-specific legal advice.'};const [id]=await db.add('compliance_screenings',[{fingerprint:fp,createdAt:new Date().toISOString(),result}]);return{id,result}.result||result;}
export async function complianceForProfile(p:any){const screen=await officialScreen(p);const gate=screen.status==='PRE_SCREEN_CLEAR'?'ALLOW_PRE_SCREEN':screen.status==='POTENTIAL_MATCH_REVIEW'?'REVIEW':screen.status==='MATCH_BLOCKED'?'BLOCK':'BLOCK';return{screening:{provider:'Free Official Sanctions Engine',mode:'OFAC + UN + UK company/entity pre-screen',status:screen.status,reason:screen.reason,checkedAt:screen.checkedAt||null,scope:screen.scope||'Company/entity pre-screen only.'},gate};}
export async function assertTransactionCompliance(p:any){if(p.role==='operator')return{ok:true,screening:{status:'OPERATOR'}};if(p.verificationStatus!=='verified')return{ok:false,status:403,message:'Transaction access is locked until Buyer/Seller verification is completed.'};const c=await complianceForProfile(p);if(c.gate!=='ALLOW_PRE_SCREEN')return{ok:false,status:423,message:'Transaction access is blocked until the Free Official Sanctions Engine completes a clear pre-screen. Current status: '+c.screening.status+'.',compliance:c};return{ok:true,compliance:c};}
export async function syncStructuredSanctions(actorId:string){const results=[];for(const source of officialSources){const fetched=await fetchStructured(source);if(fetched.status!=='HEALTHY'){results.push({sourceId:source.id,source:source.name,status:'UNAVAILABLE',records:0});continue;}let extracted:any={records:[]};try{const r=await ai.extract({content:fetched.text,prompt:'Extract a bounded structured set of sanctioned people/entities from this official sanctions source. Never invent. Prefer entities and organizations; include names, aliases, entityType, jurisdiction/country if explicit, designationDate if explicit, referenceNumber if explicit, measures if explicit. Return at most 100 records and preserve source wording.',schema:{type:'object',properties:{records:{type:'array',maxItems:100,items:{type:'object',properties:{name:{type:'string'},aliases:{type:'array',items:{type:'string'}},entityType:{type:'string'},jurisdiction:{type:'string'},designationDate:{type:'string'},referenceNumber:{type:'string'},measures:{type:'array',items:{type:'string'}}},required:['name','aliases','entityType','jurisdiction','designationDate','referenceNumber','measures']}}},required:['records']},thinkingMode:'FAST',maxTokens:7000,temperature:0.1});extracted=r.data||{records:[]};}catch{extracted={records:[]};}const records=Array.isArray(extracted.records)?extracted.records.filter((x:any)=>String(x.name||'').trim()).map((x:any)=>({canonicalId:norm(source.id+'|'+x.name+'|'+(x.referenceNumber||'')),sourceId:source.id,sourceName:source.name,sourceVersion:norm(fetched.text.slice(0,2000)),name:String(x.name).trim(),aliases:Array.isArray(x.aliases)?x.aliases.filter(Boolean).slice(0,20):[],entityType:x.entityType||'Unknown',jurisdiction:x.jurisdiction||source.jurisdiction,designationDate:x.designationDate||'',referenceNumber:x.referenceNumber||'',measures:Array.isArray(x.measures)?x.measures.filter(Boolean).slice(0,20):[],sourceUrl:source.structuredUrl,retrievedAt:new Date().toISOString(),evidenceRef:source.id+'|'+norm(x.name)+'|'+(x.referenceNumber||''),recordFingerprint:norm(source.id+'|'+x.name+'|'+(x.referenceNumber||''))})):[];if(records.length)await db.add('official_sanctions_entities',records);await db.add('audit',[{userId:actorId,action:'official_sanctions_structured_sync',sourceId:source.id,recordCount:records.length,createdAt:new Date().toISOString()}]);results.push({sourceId:source.id,source:source.name,status:records.length?'STRUCTURED_OK':'STRUCTURED_EMPTY',records:records.length,coverage:'bounded structured extraction; not exhaustive and not legal clearance'});}return results;}
export async function sanctionsGraphSnapshot(){const rows=(await db.list<any>('official_sanctions_entities',{limit:500})).items;const bySource=officialSources.map(s=>({sourceId:s.id,name:s.name,records:rows.filter((x:any)=>x.sourceId===s.id).length}));return{totalRecords:rows.length,sources:bySource,aliases:rows.reduce((n:number,x:any)=>n+(Array.isArray(x.aliases)?x.aliases.length:0),0),entities:rows.filter((x:any)=>String(x.entityType).toLowerCase().includes('entity')||String(x.entityType).toLowerCase().includes('organisation')||String(x.entityType).toLowerCase().includes('organization')).length,people:rows.filter((x:any)=>String(x.entityType).toLowerCase().includes('individual')||String(x.entityType).toLowerCase().includes('person')).length,coverage:'Bounded structured extraction from official sources; not exhaustive and never a legal clearance.'};}
