import { db } from '@appdeploy/sdk';

const STATES=['CREATED','PENDING','PAID','FAILED','EXPIRED','CANCELLED','REFUNDED','DISPUTED'] as const;
type PaymentState=typeof STATES[number];
const allowed:Record<PaymentState,PaymentState[]>={CREATED:['PENDING','CANCELLED'],PENDING:['PAID','FAILED','EXPIRED','CANCELLED'],PAID:['REFUNDED','DISPUTED'],FAILED:['PENDING','CANCELLED'],EXPIRED:['PENDING','CANCELLED'],CANCELLED:[],REFUNDED:[],DISPUTED:['REFUNDED']};
const canSee=(p:any,ownerId:string)=>p.role==='operator'||p.userId===ownerId;
async function findById(id:string){const [row]=await db.get<any>('payments',[id]);return row||null;}
export async function createPayment(user:any,input:any){const amount=Number(input.amount||0);const currency=String(input.currency||'IDR').toUpperCase().slice(0,6);const purpose=String(input.purpose||'Tradevance service').slice(0,160);const orderId=String(input.orderId||'').slice(0,120);if(!Number.isFinite(amount)||amount<=0)return{ok:false,status:400,message:'Payment amount must be greater than zero.'};if(!orderId)return{ok:false,status:400,message:'orderId is required.'};const existing=await db.list<any>('payments',{limit:100});const paymentRef='TVPAY-'+user.userId+'-'+orderId;const duplicate=existing.items.find((x:any)=>x.paymentRef===paymentRef&&['CREATED','PENDING','PAID'].includes(x.status));if(duplicate)return{ok:true,existing:true,payment:duplicate};const createdAt=new Date().toISOString();const [id]=await db.add('payments',[{paymentRef,orderId,ownerUserId:user.userId,purpose,amount,currency,provider:'Xendit',integrationState:'INTEGRATION_READY',status:'CREATED',createdAt,updatedAt:createdAt,providerReference:null,lastProviderEventId:null}]);if(!id)return{ok:false,status:500,message:'Unable to create payment record.'};return{ok:true,payment:{id,paymentRef,orderId,ownerUserId:user.userId,purpose,amount,currency,provider:'Xendit',integrationState:'INTEGRATION_READY',status:'CREATED',createdAt,updatedAt:createdAt}};}
export async function getPayment(user:any,id:string){const row=await findById(id);if(!row)return{ok:false,status:404,message:'Payment not found.'};if(!canSee(user,row.ownerUserId))return{ok:false,status:403,message:'You are not authorized to view this payment.'};return{ok:true,payment:row};}
export async function cancelPayment(user:any,id:string){const row=await findById(id);if(!row)return{ok:false,status:404,message:'Payment not found.'};if(!canSee(user,row.ownerUserId))return{ok:false,status:403,message:'You are not authorized to cancel this payment.'};const current=String(row.status) as PaymentState;if(!allowed[current]?.includes('CANCELLED'))return{ok:false,status:409,message:'This payment cannot be cancelled from its current state.'};const updated={...row,status:'CANCELLED',updatedAt:new Date().toISOString()};const ok=await db.update('payments',[{id,record:updated}]);return ok[0]?{ok:true,payment:updated}:{ok:false,status:500,message:'Unable to update payment.'};}
export async function transitionPayment(user:any,id:string,nextRaw:string,providerEventId:string|null){if(user.role!=='operator')return{ok:false,status:403,message:'Provider payment-state transitions are restricted to authorized operators.'};const row=await findById(id);if(!row)return{ok:false,status:404,message:'Payment not found.'};const next=String(nextRaw).toUpperCase() as PaymentState;if(!STATES.includes(next))return{ok:false,status:400,message:'Unsupported payment state.'};const current=String(row.status) as PaymentState;if(!allowed[current]?.includes(next))return{ok:false,status:409,message:'Invalid payment state transition.'};if(providerEventId&&row.lastProviderEventId===providerEventId)return{ok:true,idempotent:true,payment:row};const updated={...row,status:next,updatedAt:new Date().toISOString(),lastProviderEventId:providerEventId||null};const ok=await db.update('payments',[{id,record:updated}]);return ok[0]?{ok:true,payment:updated}:{ok:false,status:500,message:'Unable to persist payment state.'};}
export async function listPayments(user:any){const rows=await db.list<any>('payments',{limit:100});return{ok:true,payments:user.role==='operator'?rows.items:rows.items.filter((x:any)=>x.ownerUserId===user.userId)};}
