import { db } from '@appdeploy/sdk';
import { evaluateDealRisk } from './deal-risk';
const num=(v:any)=>Number.isFinite(Number(v))?Number(v):0;
const ownerVisible=(p:any,x:any)=>p.role==='operator'||x.ownerUserId===p.userId;
export async function predictiveAlerts(profile:any){
 const [demands,quotes,trades,profiles,learning]=await Promise.all([db.list<any>('demands',{limit:150}),db.list<any>('quotes',{limit:150}),db.list<any>('trades',{limit:120}),db.list<any>('profiles',{limit:200}),db.list<any>('trade_room_learning',{limit:100})]);
 const alerts:any[]=[];const vd=demands.items.filter((x:any)=>ownerVisible(profile,x));const vq=quotes.items.filter((x:any)=>ownerVisible(profile,x));const vt=trades.items.filter((x:any)=>ownerVisible(profile,x));
 for(const d of vd){const q=vq.filter((x:any)=>x.tradeId===d.id||x.demandId===d.id);if(['Open','Matching'].includes(String(d.status))&&q.length===0)alerts.push({id:'rfq-'+d.id,type:'RFQ_STAGNATION',severity:'High',title:'RFQ may be losing momentum',summary:`${d.product||'This requirement'} is open without a visible quote or progression.`,decision:'REVIEW',confidence:82,dataQuality:'Observed',evidence:[`Demand status: ${d.status}`,'No visible quote linked to this requirement'],action:'Review sourcing and follow-up strategy',destination:profile.role==='seller'?'Buyer Network':'Buyer Workspace'});}
 for(const t of vt){const p=profiles.items.find((x:any)=>x.userId===t.ownerUserId);if(!p)continue;const r=await evaluateDealRisk(p,{dealType:'trade',product:t.product,payment:t.payment,incoterm:t.incoterm,destination:t.destination,transactionValue:num(t.value),documents:t.documents||[]});if(r.decision==='REVIEW'||r.decision==='BLOCK')alerts.push({id:'risk-'+t.id,type:'RISK_DRIFT',severity:r.decision==='BLOCK'?'Critical':'High',title:r.decision==='BLOCK'?'Trade requires risk intervention':'Trade risk needs attention',summary:`${t.product||'Trade'} is currently ${r.decision.toLowerCase()} under the live risk policy.`,decision:r.decision,confidence:Math.max(70,Math.min(99,r.riskScore)),dataQuality:'Observed',evidence:r.reasons.slice(0,3),action:r.decision==='BLOCK'?'Resolve compliance/risk blockers before progression.':'Complete the required risk review and evidence.',destination:'Risk & Compliance'});if(Array.isArray(t.documents)&&t.documents.length===0&&['Negotiation','Contracted','In Transit','Delivered'].includes(String(t.status)))alerts.push({id:'doc-'+t.id,type:'EVIDENCE_GAP',severity:'High',title:'Execution evidence is incomplete',summary:'The trade has progressed but no transaction documents are attached yet.',decision:'REVIEW',confidence:96,dataQuality:'Observed',evidence:[`Trade status: ${t.status}`,'Document count: 0'],action:'Attach and review transaction evidence before the next material step.',destination:'Documents'});}
 if(learning.items.length>=2){const won=learning.items.filter((x:any)=>x.outcome==='won').length;const lost=learning.items.filter((x:any)=>x.outcome==='lost').length;if(won>lost)alerts.push({id:'memory-opportunity',type:'MEMORY_OPPORTUNITY',severity:'Medium',title:'Your trade memory shows a positive outcome pattern',summary:'Observed post-trade outcomes are currently more positive than negative in the visible learning set.',decision:'RECOMMEND',confidence:Math.min(94,70+learning.items.length*3),dataQuality:'Observed',evidence:[`Won outcomes: ${won}`,`Lost outcomes: ${lost}`,`Learning samples: ${learning.items.length}`],action:profile.role==='seller'?'Prioritize repeatable buyer/product patterns.':'Tighten sourcing around the product/counterparty patterns already working.',destination:'Trade Memory'});}
 if(profile.role!=='operator'){const self=profiles.items.find((x:any)=>x.userId===profile.userId);if(self&&self.verificationStatus!=='verified')alerts.push({id:'verification-'+profile.userId,type:'VERIFICATION_ATTENTION',severity:'High',title:'Your account is not transaction-ready',summary:'Verification is still required before commercial activity can progress.',decision:'REVIEW',confidence:99,dataQuality:'Observed',evidence:[`Verification status: ${self.verificationStatus||'not_verified'}`],action:'Complete Profile & Verification',destination:'Profile & Verification'});}
 const order:any={Critical:4,High:3,Medium:2,Low:1};alerts.sort((a,b)=>(order[b.severity]||0)-(order[a.severity]||0)||((b.confidence||0)-(a.confidence||0)));
 return {generatedAt:new Date().toISOString(),role:profile.role,alerts:alerts.slice(0,20),summary:{critical:alerts.filter(x=>x.severity==='Critical').length,high:alerts.filter(x=>x.severity==='High').length,medium:alerts.filter(x=>x.severity==='Medium').length,total:alerts.length},policy:'Predictive alerts are decision support only. They use observed platform data and conservative inference; they cannot approve, send, contract, pay or execute a trade.'};
}
