import { useEffect, useState } from 'react';
import { api } from '@appdeploy/client';
import { ArrowRight, BrainCircuit, CheckCircle2, CircleAlert, DatabaseZap, Gauge, ShieldCheck, Sparkles, Target, UserRoundCheck } from 'lucide-react';
import './decision-mesh.css';

export default function DecisionMesh({onNavigate,role}:{onNavigate:(x:string)=>void;role:string}){
 const [data,setData]=useState<any>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');
 useEffect(()=>{(async()=>{try{const r=await api.get('/api/decision-mesh');setData(r.data);}catch{setError('Decision Mesh is temporarily unavailable. No trade or profile data was changed.');}finally{setLoading(false);}})();},[]);
 if(loading)return <div className='page-head dm-loading'><div><div className='eyebrow'><BrainCircuit size={14}/> DECISION MESH</div><h2>Connecting live intelligence…</h2><p>Trust, risk, memory and opportunity are being assembled into one action queue.</p></div></div>;
 if(error)return <div className='admin-error'>{error}</div>;
 return <div className='decision-mesh'><div className='page-head'><div><div className='eyebrow'><BrainCircuit size={14}/> GLOBAL AI DECISION MESH</div><h2>One answer. One next action.</h2><p>Tradevance combines the intelligence already available to you and tells you what matters now, why it matters and what to do next.</p></div><div className='dm-badge'><Sparkles size={14}/> {data.role} · Governed AI</div></div>
  <section className='dm-hero'><div className='dm-hero-copy'><small>DECISION CONTEXT</small><h3>{data.summary.urgent?`You have ${data.summary.urgent} urgent decision${data.summary.urgent>1?'s':''}.`:'No critical blockers are currently detected.'}</h3><p>{data.summary.review?`${data.summary.review} item${data.summary.review>1?'s':''} need deeper review. `:''}{data.summary.recommended?`${data.summary.recommended} item${data.summary.recommended>1?'s':''} have a clear next step.`:'The system will remain conservative until more evidence appears.'}</p></div><div className='dm-kpis'><div><b>{data.summary.signals}</b><span>Live signals</span></div><div><b>{data.summary.review}</b><span>Needs review</span></div><div><b>{data.summary.memorySamples}</b><span>Learning samples</span></div></div></section>
  <div className='dm-layout'><section className='panel'><div className='panel-title dm-panel-title'><div className='title-icon'><Target size={16}/></div><div><h3>What needs your attention</h3><p>Prioritized from live platform signals.</p></div></div><div className='dm-list'>{data.cards.map((c:any)=><div className={'dm-card '+c.priority} key={c.type+'-'+c.id}><div className='dm-card-top'><div className='dm-card-icon'>{c.decision==='BLOCK'?<CircleAlert size={17}/>:c.decision==='REVIEW'?<ShieldCheck size={17}/>:<CheckCircle2 size={17}/>}</div><div className='dm-card-title'><small>{c.type}</small><b>{c.title}</b><span>{c.subtitle}</span></div><span className={'dm-decision '+String(c.decision).toLowerCase()}>{c.decision}</span></div><div className='dm-score'><div><span>Confidence</span><b>{c.confidence}%</b></div><div className='dm-bar'><i style={{width:`${Math.min(100,Math.max(0,c.confidence))}%`}}/></div></div><div className='dm-reasons'>{c.why.map((r:string)=><span key={r}>{r}</span>)}</div><div className='dm-footer'><div className='dm-evidence'><DatabaseZap size={13}/><span>{c.dataQuality} evidence · {c.evidence[0]}</span></div><button className='text-btn' onClick={()=>onNavigate(c.destination)}>{c.nextAction}<ArrowRight size={13}/></button></div></div>)}</div></section><aside className='dm-side'><section className='panel dm-context'><div className='panel-title'><div className='title-icon'><Gauge size={16}/></div><div><h3>How Tradevance decides</h3><p>Signals, not black-box commands.</p></div></div><div className='dm-principles'>{data.principles.map((x:string)=><div key={x}><CheckCircle2 size={14}/><span>{x}</span></div>)}</div></section><section className='panel dm-memory'><div className='panel-title'><div className='title-icon'><UserRoundCheck size={16}/></div><div><h3>Memory coverage</h3><p>How much observed history is available to this view.</p></div></div><div className='dm-memory-value'><b>{data.memory.coveragePercent}%</b><span>coverage</span></div><div className='dm-memory-bar'><i style={{width:`${Math.min(100,data.memory.coveragePercent)}%`}}/></div><small>{data.memory.tradeRecords} trade records · {data.memory.quoteRecords} quotes · {data.memory.learningSamples} learning samples</small></section></aside></div></div>;
}
