import { useEffect, useMemo, useState } from 'react';
import { api } from '@appdeploy/client';
import { AlertTriangle, CheckCircle2, ExternalLink, Filter, Globe2, Search, ShieldCheck, Sparkles, TrendingUp, X } from 'lucide-react';
import './entity.css';

type Evidence={type:string;claim:string;sourceUrl?:string};
type Entity={id:string;name:string;entityType:'Buyer'|'Seller';country:string;products:string[];verificationLevel:string;confidence:number;evidence:Evidence[];officialUrl?:string;tradeEvidence?:string;lastVerified:string;notes:string};
export default function EntityIntelligence(){
 const [entities,setEntities]=useState<Entity[]>([]);const [q,setQ]=useState('');const [type,setType]=useState('All');const [product,setProduct]=useState('All');const [selected,setSelected]=useState<Entity|null>(null);const [loading,setLoading]=useState(true);const [verifyUrl,setVerifyUrl]=useState('');const [verifyResult,setVerifyResult]=useState<any>(null);const [verifying,setVerifying]=useState(false);const [verifyError,setVerifyError]=useState('');
 const refresh=()=>api.get('/api/entities').then(r=>setEntities(r.data.entities)).catch(()=>setEntities([])).finally(()=>setLoading(false));useEffect(()=>{refresh();},[]);
 const products=useMemo(()=>['All',...Array.from(new Set(entities.flatMap(e=>e.products))).sort()],[entities]);
 const filtered=entities.filter(e=>(type==='All'||e.entityType===type)&&(product==='All'||e.products.includes(product))&&(!q||[e.name,e.country,e.products.join(' ')].join(' ').toLowerCase().includes(q.toLowerCase()))).sort((a,b)=>b.confidence-a.confidence);
 const verify=async()=>{setVerifyError('');setVerifyResult(null);if(!verifyUrl.trim())return;setVerifying(true);try{const r=await api.post('/api/entities/verify-url',{url:verifyUrl.trim(),companyName:selected?.name});setVerifyResult(r.data);}catch{setVerifyError('Verification failed. Check the URL and try again.');}finally{setVerifying(false);}};
 return <div className='entity-page'>
  <div className='page-head'><div><div className='eyebrow'><Globe2 size={14}/> GLOBAL ENTITY INTELLIGENCE</div><h2>Evidence-backed buyer & seller network</h2><p>Public-source discovery with provenance, confidence and trade-evidence layers. This is intelligence, not a legal guarantee.</p></div></div>
  <div className='entity-banner'><div><b>Verification architecture</b><span>Discovered → Source Verified → Evidence-backed → Document Verified → Trade Verified → Transaction Verified</span></div><div className='entity-count'>{entities.length} entities in current registry</div></div>
  <section className='entity-toolbar'><div className='entity-search'><Search size={15}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder='Search company, country or product...'/></div><div className='entity-filters'><Filter size={14}/><select value={type} onChange={e=>setType(e.target.value)}><option>All</option><option>Buyer</option><option>Seller</option></select><select value={product} onChange={e=>setProduct(e.target.value)}>{products.map(p=><option key={p}>{p}</option>)}</select></div></section>
  {loading?<div className='entity-empty'>Loading evidence-backed entity registry…</div>:<div className='entity-grid'>{filtered.map(e=><button className='entity-card' key={e.id} onClick={()=>{setSelected(e);setVerifyResult(null);setVerifyError('');setVerifyUrl(e.officialUrl||'')}}><div className='entity-card-top'><div className='entity-avatar'>{e.name.slice(0,2).toUpperCase()}</div><div className='entity-name'><b>{e.name}</b><span>{e.entityType} · {e.country}</span></div><div className='confidence'><strong>{e.confidence}</strong><small>CONF.</small></div></div><div className='entity-products'>{e.products.map(p=><span key={p}>{p}</span>)}</div><div className='entity-status'><span><ShieldCheck size={13}/> {e.verificationLevel}</span><span><TrendingUp size={13}/> {e.lastVerified}</span></div><div className='entity-foot'><span>{e.evidence.length} evidence signals</span><span>Open dossier <ExternalLink size={12}/></span></div></button>)}</div>}
  {selected&&<div className='entity-drawer-backdrop' onClick={()=>setSelected(null)}><aside className='entity-drawer' onClick={e=>e.stopPropagation()}><button className='drawer-close' onClick={()=>setSelected(null)}><X size={18}/></button><div className='eyebrow'><ShieldCheck size={14}/> ENTITY DOSSIER</div><h3>{selected.name}</h3><p>{selected.entityType} · {selected.country}</p><div className='dossier-score'><strong>{selected.confidence}</strong><span>evidence confidence</span></div><div className='dossier-block'><b>Verification level</b><span>{selected.verificationLevel}</span></div><div className='dossier-block'><b>Products / demand signals</b><span>{selected.products.join(' · ')}</span></div><div className='dossier-block'><b>Evidence</b>{selected.evidence.map((x,i)=><div className='evidence-row' key={i}><CheckCircle2 size={14}/><span><strong>{x.type}</strong> — {x.claim}{x.sourceUrl&&<> · <a href={x.sourceUrl} target='_blank' rel='noreferrer'>source</a></>}</span></div>)}</div><div className='dossier-block'><b>Live website verification</b><div className='verify-form'><input value={verifyUrl} onChange={e=>setVerifyUrl(e.target.value)} placeholder='https://company.com'/><button className='btn primary' onClick={verify} disabled={verifying}>{verifying?<Sparkles size={14}/>:<ShieldCheck size={14}/>} {verifying?'Verifying…':'Verify website'}</button></div>{verifyError&&<div className='verify-error'>{verifyError}</div>}{verifyResult&&<div className='verify-result'><b>{verifyResult.signals.companyNameHint}</b><span>Status {verifyResult.signals.status} · {verifyResult.signals.title||'No title'}</span><span>Supplier signals: {verifyResult.signals.keywords.supplier?'Detected':'Not detected'} · Buyer signals: {verifyResult.signals.keywords.buyer?'Detected':'Not detected'}</span><span>Products detected: {verifyResult.signals.keywords.products.join(' · ')||'None'}</span><small>{verifyResult.excerpt}</small></div>}</div><div className='dossier-block'><b>Assessment note</b><span>{selected.notes}</span></div>{selected.officialUrl&&<a className='official-link' href={selected.officialUrl} target='_blank' rel='noreferrer'>Open official source <ExternalLink size={13}/></a>}<div className='disclaimer'><AlertTriangle size={14}/> Tradevance evidence status is an intelligence layer. Final KYC/KYB, sanctions, UBO and transaction verification require licensed/contracted data sources and direct documentary checks.</div></aside></div>}
 </div>;
}
